---
# tasks file for gameoflife
  - fail:
      msg: "try to perform this task on ubuntu"
    when: 
    - ansible_os_family != "Debian"
  - debug:
      msg: "initilizting the task"
  - name: "getting and verifing key"
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  - name: "installing packing"
    apt:
      name: "{{item}}"
      deb: https://apt.kubernetes.io/ kubernetes-xenial main
      update_cache: yes
      state: present
    with_items:
        - kubelet
        - kubeadm
        - kubectl
  - name: "apt-mark"
    command: apt-mark hold kubelet kubeadm kubectl
    
