---
# tasks file for gameoflife
  - fail:
      msg: "try to perform this task on ubuntu"
    when: 
    - ansible_os_family != "Debian"
  - debug:
      msg: "initilizting the task"
  - name: "updating apt repository"
    apt:
      name: {{item}}
      update_cache: yes
      state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
  - name: "adding key"
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: "updating apt repository"
    apt_repository: 
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable 
      state: present
  - name: "installing docker"
    apt:
      name: docker-ce=18.06.2~ce~3-0~ubuntu
      update_cache: yes
      state: present
  - name: "copying daemon file"
    copy:
      src: docker/daemon.json
      dest: /etc/docker/
  - name: "making directory"
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
  - name: "adding daemon"
    systemd: 
      daemon_reload: yes
      name: docker
      state: restarted

    
      
      

       